theme: jekyll-theme-minimal
title: ADA Project
description: Representations of violence and public appraisal
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
